### ISSUE TITLE
Bug in 1.6.8 version

### ISSUE THREAD

**Issue by mthang1112** [tmizu23/demtool#1]
I am currently using this tool to convert FGD DEM to Tiff file. However, I encounter the issue in  1.6.8 version.

For the same dataset, when I use 1.6.7 version, I can convert without any problems. However, when using 1.6.8 version, I got the message "FG-GML-5339-57-49-DEM5A-20161001.xml projection is different, Exit this program", therefore, the process is canceled.

Here is the list of my dataset: (Downloaded from https://fgd.gsi.go.jp/)
FG-GML-5339-57-DEM5A.zip
FG-GML-5339-67-DEM5A.zip
FG-GML-5340-50-DEM5A.zip
FG-GML-5340-51-DEM5A.zip
FG-GML-5340-60-DEM5A.zip
FG-GML-5340-61-DEM5A.zip

**Comment by tmizu23** [comment]
I fix it ver 1.6.9.
This was caused of  data files difference of this line.
<gml:Envelope  srsName="fguuid:jgd2011.bl">

Some files space is one or two between "Envelope" and "srsName".

So I fix it to read only  "jguuid:jgd"
Thank you for your report.

**Comment by Serranowski** [comment]
I am getting the same error on version 1.7.1; the problematic file in question is **FG-GML-3622-57-DEM10B-20190510**. I see some of my files are  _<gml:Envelope srsName="fguuid:jgd2011.bl">_ while some others are _<gml:Envelope srsName="fguuid:jgd2000.bl">_ instead

**Comment by tmizu23** [comment]
@Serranowski 
This is not a bug. The geodetic systems of the files are different. Files with different geodetic systems cannot be processed together. You should process them separately, or you may be able to process them by editing the files at your own risk.
